modLoader="javafml"
loaderVersion="[29,)"
issueTrackerURL="https://github.com/Christofmeg/NoBlazeKnockback/issues"
license="The MIT License (MIT)"
[[mods]]
    modId="noblazeknockback"
    version="${version}"
    displayName="No Blaze Knockback"
    displayURL="https://github.com/Christofmeg/NoBlazeKnockback"
    logoFile="icon.png"
    authors="Christofmeg"
    description="Prevents knockback from Basalz, Blaze, Blitz and Blizz projectiles."
[[dependencies.noblazeknockback]]
    modId="forge"
    mandatory=true
    versionRange="[29,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.noblazeknockback]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,1.16)"
    ordering="NONE"
    side="BOTH"
